name: Publish package as Github release & Docker init container

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'


jobs:
  release-github-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build a project & run unit tests
        run: ./gradlew test

      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: ${{ secrets.DOCKER_URL }}/${{ github.event.repository.name }}
          flavor: latest=true
          tags: |
            type=raw,value==${{ env.TAG }}
            type=ref,event=branch
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_URL }}
          username: ${{ secrets.REGISTRY_AUTH_USERNAME }}
          password: ${{ secrets.REGISTRY_AUTH_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: src/main/docker/initContainer.Dockerfile
          build-args: VERSION=${{ env.TAG }}
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
