name: Publish package as Github release & Docker init container

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'


jobs:
  release-github-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build a project & run unit tests
        run: ./gradlew test

      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Set version from git tag
        run: ./gradlew jar -P version=${{ env.TAG }}

      - name: Build Docker init container
        run: |
          docker build \
          --build-arg VERSION=${{ env.TAG }} \
          -f src/main/docker/initContainer.Dockerfile \
          -t aerogear/keycloak-metrics-spi:${{ env.TAG }} \
          -t aerogear/keycloak-metrics-spi:latest \
          .
      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_URL }}
          username: ${{ secrets.REGISTRY_AUTH_USERNAME }}
          password: ${{ secrets.REGISTRY_AUTH_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}
